---
path: '/home/msackel/Desktop/gammaClassification/data/complete_Datasets/dataCrab'

set_params:
    n_estimators: 100
    n_jobs: 20
    verbose: 1 
    bootstrap: True

loop_params:
    max_depth: 
        - 7 
        - 9
    max_features:  
        - 3
        - 4
    
grid_params:
    cv: 2
    scoring: 'roc_auc'

plot_feature:
    feature_one: 'max_depth'
    feature_two: 'max_features'
