---
- conc_core
- concentration_one_pixel    
- concentration_two_pixel
- leakage
- leakage2 
- size 
- width
- num_islands
- num_pixel_in_shower 
- ph_charge_shower_max
- ph_charge_shower_mean
- ph_charge_shower_variance
